<?php defined('ABSPATH') or die();

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class NUNO_SARMENTO_SOCIAL_ICONS_Class {

	private $tend_tdsocialicons_class_options;
	private $options_about;
	private $options_report;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'tend_tdsocialicons_class_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'tend_tdsocialicons_class_page_init' ) );
	}

	public function tend_tdsocialicons_class_add_plugin_page() {
		add_menu_page(
			'NS Social Bar', // page_title
			'NS Social Bar', // menu_title
			'manage_options', // capability
			'nuno-sarmento-socialicons', // menu_slug
			array( $this, 'tend_tdsocialicons_class_create_admin_page' ), // call back function
			'dashicons-networking', // icon_url
			24 // position
		);
	}

	public function tend_tdsocialicons_class_create_admin_page() {

		$this->tend_tdsocialicons_class_options = get_option( 'tend_tdsocialicons_class_option_name' );
		$this->options_about = get_option( 'ns_socialicons_about' );
		$this->options_report = get_option( 'ns_socialicons_report' );
		$about_Screen = ( isset( $_GET['action'] ) && 'about' == $_GET['action'] ) ? true : false;
    $report_Screen = ( isset( $_GET['action'] ) && 'report' == $_GET['action'] ) ? true : false;

		?>

		<style media="screen">
			.header__ns_nsss:after { content: " "; display: block; height: 29px; width: 15%; position: absolute;
				top: 1%; right: 25px; background-image: url(//ps.w.org/nuno-sarmento-social-icons/assets/icon-128x128.png?rev=1588574); background-size:128px 128px; height: 128px; width: 128px;
			}
			.header__ns_nsss{ background: white; height: 150px; width: 100%; float: left;}
			.header__ns_nsss h2 {padding: 35px;font-size: 27px;}
			@media only screen and (max-width: 480px) {
				.header__ns_nsss:after { content: " "; display: block; height: 29px; width: 15%; position: absolute;
					top: 6%; right: 25px; background-image: url(//ps.w.org/nuno-sarmento-social-icons/assets/icon-128x128.png?rev=1588574); background-size:50px 50px; height: 50px; width: 50px;
				}
			}
		</style>

		<div class="wrap">
		<div class="header__ns_nsss">
			<h2><?php echo NUNO_SARMENTO_SOCIALICONS_NAME; ?></h2>
		</div>
			<h2 class="nav-tab-wrapper">
				<a href="<?php echo admin_url( 'admin.php?page=nuno-sarmento-socialicons' ); ?>" class="nav-tab<?php if ( ! isset( $_GET['action'] ) || isset( $_GET['action'] ) && 'about' != $_GET['action']  && 'report' != $_GET['action'] ) echo ' nav-tab-active'; ?>"><?php esc_html_e( 'Settings' ); ?></a>
				<a href="<?php echo esc_url( add_query_arg( array( 'action' => 'about' ), admin_url( 'admin.php?page=nuno-sarmento-socialicons' ) ) ); ?>" class="nav-tab<?php if ( $about_Screen ) echo ' nav-tab-active'; ?>"><?php esc_html_e( 'Other Plugins' ); ?></a>
				<a href="<?php echo esc_url( add_query_arg( array( 'action' => 'report' ), admin_url( 'admin.php?page=nuno-sarmento-socialicons' ) ) ); ?>" class="nav-tab<?php if ( $report_Screen ) echo ' nav-tab-active'; ?>"><?php esc_html_e( 'System Report' ); ?></a>
			</h2>

			<?php settings_errors(); ?>

		 <form method="post" action="options.php">
			 <?php
				 if($about_Screen) {
					settings_fields( 'ns_socialicons_about' );
					do_settings_sections( 'ns-socialicons-setting-about' );

				} elseif($report_Screen) {
					settings_fields( 'ns_socialicons_report' );
					do_settings_sections( 'ns-socialicons-setting-report' );

				}else {
					settings_fields( 'tend_tdsocialicons_class_option_group' );
					do_settings_sections( 'nuno-sarmento-socialicons-class-admin' );
					submit_button();
				}
			?>
		</form>
	 </div>


	<?php }

	public function tend_tdsocialicons_class_page_init() {
		register_setting(
			'tend_tdsocialicons_class_option_group', // option_group
			'tend_tdsocialicons_class_option_name', // option_name
			array( $this, 'tend_tdsocialicons_class_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'tend_tdsocialicons_class_setting_section', // id
			__( 'Social Icons', 'nuno-sarmento-socialicons' ), // title
			array( $this, 'tend_tdsocialicons_class_section_info' ), // callback
			'nuno-sarmento-socialicons-class-admin' // page
		);

		add_settings_field(
			'social_bar_disable_0', // id
			__( 'Social bar (disable)', 'nuno-sarmento-socialicons' ), // title
			array( $this, 'social_bar_disable_0_callback' ), // callback
			'nuno-sarmento-socialicons-class-admin', // page
			'tend_tdsocialicons_class_setting_section' // section
		);

		add_settings_field(
			'facebook_url_1', // id
			__( 'Facebook url', 'nuno-sarmento-socialicons' ), // title
			array( $this, 'facebook_url_1_callback' ), // callback
			'nuno-sarmento-socialicons-class-admin', // page
			'tend_tdsocialicons_class_setting_section' // section
		);

		add_settings_field(
			'enable_facebook_2', // id
			__( 'Enable Facebook', 'nuno-sarmento-socialicons' ), // title
			array( $this, 'enable_facebook_2_callback' ), // callback
			'nuno-sarmento-socialicons-class-admin', // page
			'tend_tdsocialicons_class_setting_section' // section
		);

		add_settings_field(
			'linkedin_3', // id
			__( 'Linkedin', 'nuno-sarmento-socialicons' ), // title
			array( $this, 'linkedin_3_callback' ), // callback
			'nuno-sarmento-socialicons-class-admin', // page
			'tend_tdsocialicons_class_setting_section' // section
		);

		add_settings_field(
			'enable_linkedin_4', // id
			__( 'Enable Linkedin', 'nuno-sarmento-socialicons' ), // title
			array( $this, 'enable_linkedin_4_callback' ), // callback
			'nuno-sarmento-socialicons-class-admin', // page
			'tend_tdsocialicons_class_setting_section' // section
		);

		add_settings_field(
			'twitter_5', // id
			__( 'Twitter', 'nuno-sarmento-socialicons' ), // title
			array( $this, 'twitter_5_callback' ), // callback
			'nuno-sarmento-socialicons-class-admin', // page
			'tend_tdsocialicons_class_setting_section' // section
		);

		add_settings_field(
			'enable_twitter_6', // id
			__( 'Enable Twitter', 'nuno-sarmento-socialicons' ), // title
			array( $this, 'enable_twitter_6_callback' ), // callback
			'nuno-sarmento-socialicons-class-admin', // page
			'tend_tdsocialicons_class_setting_section' // section
		);

		add_settings_field(
			'instagram_7', // id
			__( 'Instagram', 'nuno-sarmento-socialicons' ), // title
			array( $this, 'instagram_7_callback' ), // callback
			'nuno-sarmento-socialicons-class-admin', // page
			'tend_tdsocialicons_class_setting_section' // section
		);

		add_settings_field(
			'enable_instagram_8', // id
			__( 'Enable Instagram', 'nuno-sarmento-socialicons' ), // title
			array( $this, 'enable_instagram_8_callback' ), // callback
			'nuno-sarmento-socialicons-class-admin', // page
			'tend_tdsocialicons_class_setting_section' // section
		);

		add_settings_field(
			'dribbble_9', // id
			__( 'Dribbble', 'nuno-sarmento-socialicons' ), // title
			array( $this, 'dribbble_9_callback' ), // callback
			'nuno-sarmento-socialicons-class-admin', // page
			'tend_tdsocialicons_class_setting_section' // section
		);

		add_settings_field(
			'enable_dribbble_10', // id
			__( 'Enable Dribbble', 'nuno-sarmento-socialicons' ), // title
			array( $this, 'enable_dribbble_10_callback' ), // callback
			'nuno-sarmento-socialicons-class-admin', // page
			'tend_tdsocialicons_class_setting_section' // section
		);

		add_settings_field(
			'behance_11', // id
			__( 'Behance', 'nuno-sarmento-socialicons' ), // title
			array( $this, 'behance_11_callback' ), // callback
			'nuno-sarmento-socialicons-class-admin', // page
			'tend_tdsocialicons_class_setting_section' // section
		);

		add_settings_field(
			'enable_behance_12', // id
			__( 'Enable Behance', 'nuno-sarmento-socialicons' ), // title
			array( $this, 'enable_behance_12_callback' ), // callback
			'nuno-sarmento-socialicons-class-admin', // page
			'tend_tdsocialicons_class_setting_section' // section
		);

		add_settings_field(
			'googleplus_13', // id
			__( 'Google+', 'nuno-sarmento-socialicons' ), // title
			array( $this, 'googleplus_13_callback' ), // callback
			'nuno-sarmento-socialicons-class-admin', // page
			'tend_tdsocialicons_class_setting_section' // section
		);

		add_settings_field(
			'googleplus_14', // id
			__( 'Enable Google+', 'nuno-sarmento-socialicons' ), // title
			array( $this, 'enable_googleplus_14_callback' ), // callback
			'nuno-sarmento-socialicons-class-admin', // page
			'tend_tdsocialicons_class_setting_section' // section
		);

		add_settings_field(
			'colorpicker_15', // id
			__( 'Main Color Background', 'nuno-sarmento-socialicons' ), // title
			array( $this, 'colorpicker_15_callback' ), // callback
			'nuno-sarmento-socialicons-class-admin', // page
			'tend_tdsocialicons_class_setting_section' // section
		);

		add_settings_field(
			'colorpicker_17', // id
			__( 'Icon - Inner Colour', 'nuno-sarmento-socialicons' ), // title
			array( $this, 'colorpicker_17_callback' ), // callback
			'nuno-sarmento-socialicons-class-admin', // page
			'tend_tdsocialicons_class_setting_section' // section
		);

		add_settings_field(
			'colorpicker_18', // id
			__( 'Icon - Outer Colour', 'nuno-sarmento-socialicons' ), // title
			array( $this, 'colorpicker_18_callback' ), // callback
			'nuno-sarmento-socialicons-class-admin', // page
			'tend_tdsocialicons_class_setting_section' // section
		);

		add_settings_field(
			'colorpicker_19', // id
			__( 'Main Color Background ( hover )', 'nuno-sarmento-socialicons' ), // title
			array( $this, 'colorpicker_19_callback' ), // callback
			'nuno-sarmento-socialicons-class-admin', // page
			'tend_tdsocialicons_class_setting_section' // section
		);

		add_settings_field(
			'colorpicker_16', // id
			__( 'Icon - Outer Colour ( hover )', 'nuno-sarmento-socialicons' ), // title
			array( $this, 'colorpicker_16_callback' ), // callback
			'nuno-sarmento-socialicons-class-admin', // page
			'tend_tdsocialicons_class_setting_section' // section
		);

		add_settings_field(
			'colorpicker_20', // id
			__( 'Icon - Inner Colour ( hover )', 'nuno-sarmento-socialicons' ), // title
			array( $this, 'colorpicker_20_callback' ), // callback
			'nuno-sarmento-socialicons-class-admin', // page
			'tend_tdsocialicons_class_setting_section' // section
		);


		// About Page register
		register_setting(
	      'ns_socialicons_about', // Option group
	      'ns_socialicons_about', // Option name
	      array( $this, 'ns_socialicons_about_callback' ) // Sanitize
    );

    add_settings_section(
        'tend_tdsocialicons_class_setting_section', // ID
        '', // Title
        array( $this, 'ns_socialicons_about_callback' ), // Callback
        'ns-socialicons-setting-about' // Page
    );

		// Sytem Report register
		register_setting(
        'ns_socialicons_report', // Option group
        'ns_socialicons_report', // Option name
        array( $this, 'ns_socialicons_snapshot_report' ) // Sanitize
    );

	  add_settings_section(
	      'tend_tdsocialicons_class_setting_section', // ID
	      '', // Title
	      array( $this, 'ns_socialicons_snapshot_report' ), // Callback
	      'ns-socialicons-setting-report' // Page
	  );


	}

	public function tend_tdsocialicons_class_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['social_bar_disable_0'] ) ) {
			$sanitary_values['social_bar_disable_0'] = $input['social_bar_disable_0'];
		}

		if ( isset( $input['facebook_url_1'] ) ) {
			$sanitary_values['facebook_url_1'] = sanitize_text_field( $input['facebook_url_1'] );
		}

		if ( isset( $input['enable_facebook_2'] ) ) {
			$sanitary_values['enable_facebook_2'] = $input['enable_facebook_2'];
		}

		if ( isset( $input['linkedin_3'] ) ) {
			$sanitary_values['linkedin_3'] = sanitize_text_field( $input['linkedin_3'] );
		}

		if ( isset( $input['enable_linkedin_4'] ) ) {
			$sanitary_values['enable_linkedin_4'] = $input['enable_linkedin_4'];
		}

		if ( isset( $input['twitter_5'] ) ) {
			$sanitary_values['twitter_5'] = sanitize_text_field( $input['twitter_5'] );
		}

		if ( isset( $input['enable_twitter_6'] ) ) {
			$sanitary_values['enable_twitter_6'] = $input['enable_twitter_6'];
		}

		if ( isset( $input['instagram_7'] ) ) {
			$sanitary_values['instagram_7'] = sanitize_text_field( $input['instagram_7'] );
		}

		if ( isset( $input['enable_instagram_8'] ) ) {
			$sanitary_values['enable_instagram_8'] = $input['enable_instagram_8'];
		}

		if ( isset( $input['dribbble_9'] ) ) {
			$sanitary_values['dribbble_9'] = sanitize_text_field( $input['dribbble_9'] );
		}

		if ( isset( $input['enable_dribbble_10'] ) ) {
			$sanitary_values['enable_dribbble_10'] = $input['enable_dribbble_10'];
		}

		if ( isset( $input['behance_11'] ) ) {
			$sanitary_values['behance_11'] = sanitize_text_field( $input['behance_11'] );
		}

		if ( isset( $input['enable_behance_12'] ) ) {
			$sanitary_values['enable_behance_12'] = $input['enable_behance_12'];
		}

		if ( isset( $input['googleplus_13'] ) ) {
			$sanitary_values['googleplus_13'] = sanitize_text_field( $input['googleplus_13'] );
		}

		if ( isset( $input['enable_googleplus_14'] ) ) {
			$sanitary_values['enable_googleplus_14'] = $input['enable_googleplus_14'];
		}

		if ( isset( $input['colorpicker_15'] ) ) {
			$sanitary_values['colorpicker_15'] = $input['colorpicker_15'];
		}

		if ( isset( $input['colorpicker_16'] ) ) {
			$sanitary_values['colorpicker_16'] = $input['colorpicker_16'];
		}

		if ( isset( $input['colorpicker_17'] ) ) {
			$sanitary_values['colorpicker_17'] = $input['colorpicker_17'];
		}

		if ( isset( $input['colorpicker_18'] ) ) {
			$sanitary_values['colorpicker_18'] = $input['colorpicker_18'];
		}

		if ( isset( $input['colorpicker_19'] ) ) {
			$sanitary_values['colorpicker_19'] = $input['colorpicker_19'];
		}

		if ( isset( $input['colorpicker_20'] ) ) {
			$sanitary_values['colorpicker_20'] = $input['colorpicker_20'];
		}

		return $sanitary_values;
	}


	 /**
	 * helper function for number conversions
	 *
	 * @access public
	 * @param mixed $v
	 * @return void
	 */

	public function num_convt( $v ) {
		$l   = substr( $v, -1 );
		$ret = substr( $v, 0, -1 );

		switch ( strtoupper( $l ) ) {
			case 'P': // fall-through
			case 'T': // fall-through
			case 'G': // fall-through
			case 'M': // fall-through
			case 'K': // fall-through
				$ret *= 1024;
				break;
			default:
				break;
		}

		return $ret;
	}

	public function tend_tdsocialicons_class_section_info() {

	}

	public function social_bar_disable_0_callback() {
		?> <select name="tend_tdsocialicons_class_option_name[social_bar_disable_0]" id="social_bar_disable_0">
			<?php $selected = (isset( $this->tend_tdsocialicons_class_options['social_bar_disable_0'] ) && $this->tend_tdsocialicons_class_options['social_bar_disable_0'] === 'none') ? 'selected' : '' ; ?>
			<option value="none" <?php echo $selected; ?>><?php _e('Disable','nuno-sarmento-socialicons'); ?></option>
			<?php $selected = (isset( $this->tend_tdsocialicons_class_options['social_bar_disable_0'] ) && $this->tend_tdsocialicons_class_options['social_bar_disable_0'] === 'block') ? 'selected' : '' ; ?>
			<option value="block" <?php echo $selected; ?>><?php _e('Enable','nuno-sarmento-socialicons'); ?></option>
		</select> <?php
	}

	public function facebook_url_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="tend_tdsocialicons_class_option_name[facebook_url_1]" id="facebook_url_1" value="%s">',
			isset( $this->tend_tdsocialicons_class_options['facebook_url_1'] ) ? esc_attr( $this->tend_tdsocialicons_class_options['facebook_url_1']) : ''
		);
	}

	public function enable_facebook_2_callback() {
		?> <fieldset><?php $checked = ( isset( $this->tend_tdsocialicons_class_options['enable_facebook_2'] ) && $this->tend_tdsocialicons_class_options['enable_facebook_2'] === 'block' ) ? 'checked' : '' ; ?>
		<label for="enable_facebook_2-0"><input type="radio" name="tend_tdsocialicons_class_option_name[enable_facebook_2]" id="enable_facebook_2-0" value="block" <?php echo $checked; ?>> <?php _e('Enable','nuno-sarmento-socialicons'); ?></label><br>
		<?php $checked = ( isset( $this->tend_tdsocialicons_class_options['enable_facebook_2'] ) && $this->tend_tdsocialicons_class_options['enable_facebook_2'] === 'none' ) ? 'checked' : '' ; ?>
		<label for="enable_facebook_2-1"><input type="radio" name="tend_tdsocialicons_class_option_name[enable_facebook_2]" id="enable_facebook_2-1" value="none" <?php echo $checked; ?>> <?php _e('Disable','nuno-sarmento-socialicons'); ?></label></fieldset> <?php
	}

	public function linkedin_3_callback() {
		printf(
			'<input class="regular-text" type="text" name="tend_tdsocialicons_class_option_name[linkedin_3]" id="linkedin_3" value="%s">',
			isset( $this->tend_tdsocialicons_class_options['linkedin_3'] ) ? esc_attr( $this->tend_tdsocialicons_class_options['linkedin_3']) : ''
		);
	}

	public function enable_linkedin_4_callback() {
		?> <fieldset><?php $checked = ( isset( $this->tend_tdsocialicons_class_options['enable_linkedin_4'] ) && $this->tend_tdsocialicons_class_options['enable_linkedin_4'] === 'block' ) ? 'checked' : '' ; ?>
		<label for="enable_linkedin_4-0"><input type="radio" name="tend_tdsocialicons_class_option_name[enable_linkedin_4]" id="enable_linkedin_4-0" value="block" <?php echo $checked; ?>> <?php _e('Enable','nuno-sarmento-socialicons'); ?></label><br>
		<?php $checked = ( isset( $this->tend_tdsocialicons_class_options['enable_linkedin_4'] ) && $this->tend_tdsocialicons_class_options['enable_linkedin_4'] === 'none' ) ? 'checked' : '' ; ?>
		<label for="enable_linkedin_4-1"><input type="radio" name="tend_tdsocialicons_class_option_name[enable_linkedin_4]" id="enable_linkedin_4-1" value="none" <?php echo $checked; ?>> <?php _e('Disable','nuno-sarmento-socialicons'); ?></label></fieldset> <?php
	}

	public function twitter_5_callback() {
		printf(
			'<input class="regular-text" type="text" name="tend_tdsocialicons_class_option_name[twitter_5]" id="twitter_5" value="%s">',
			isset( $this->tend_tdsocialicons_class_options['twitter_5'] ) ? esc_attr( $this->tend_tdsocialicons_class_options['twitter_5']) : ''
		);
	}

	public function enable_twitter_6_callback() {
		?> <fieldset><?php $checked = ( isset( $this->tend_tdsocialicons_class_options['enable_twitter_6'] ) && $this->tend_tdsocialicons_class_options['enable_twitter_6'] === 'block' ) ? 'checked' : '' ; ?>
		<label for="enable_twitter_6-0"><input type="radio" name="tend_tdsocialicons_class_option_name[enable_twitter_6]" id="enable_twitter_6-0" value="block" <?php echo $checked; ?>> <?php _e('Enable','nuno-sarmento-socialicons'); ?></label><br>
		<?php $checked = ( isset( $this->tend_tdsocialicons_class_options['enable_twitter_6'] ) && $this->tend_tdsocialicons_class_options['enable_twitter_6'] === 'none' ) ? 'checked' : '' ; ?>
		<label for="enable_twitter_6-1"><input type="radio" name="tend_tdsocialicons_class_option_name[enable_twitter_6]" id="enable_twitter_6-1" value="none" <?php echo $checked; ?>> <?php _e('Disable','nuno-sarmento-socialicons'); ?></label></fieldset> <?php
	}

	public function instagram_7_callback() {
		printf(
			'<input class="regular-text" type="text" name="tend_tdsocialicons_class_option_name[instagram_7]" id="instagram_7" value="%s">',
			isset( $this->tend_tdsocialicons_class_options['instagram_7'] ) ? esc_attr( $this->tend_tdsocialicons_class_options['instagram_7']) : ''
		);
	}

	public function enable_instagram_8_callback() {
		?> <fieldset><?php $checked = ( isset( $this->tend_tdsocialicons_class_options['enable_instagram_8'] ) && $this->tend_tdsocialicons_class_options['enable_instagram_8'] === 'block' ) ? 'checked' : '' ; ?>
		<label for="enable_instagram_8-0"><input type="radio" name="tend_tdsocialicons_class_option_name[enable_instagram_8]" id="enable_instagram_8-0" value="block" <?php echo $checked; ?>> <?php _e('Enable','nuno-sarmento-socialicons'); ?></label><br>
		<?php $checked = ( isset( $this->tend_tdsocialicons_class_options['enable_instagram_8'] ) && $this->tend_tdsocialicons_class_options['enable_instagram_8'] === 'none' ) ? 'checked' : '' ; ?>
		<label for="enable_instagram_8-1"><input type="radio" name="tend_tdsocialicons_class_option_name[enable_instagram_8]" id="enable_instagram_8-1" value="none" <?php echo $checked; ?>> <?php _e('Disable','nuno-sarmento-socialicons'); ?></label></fieldset> <?php
	}

	public function dribbble_9_callback() {
		printf(
			'<input class="regular-text" type="text" name="tend_tdsocialicons_class_option_name[dribbble_9]" id="dribbble_9" value="%s">',
			isset( $this->tend_tdsocialicons_class_options['dribbble_9'] ) ? esc_attr( $this->tend_tdsocialicons_class_options['dribbble_9']) : ''
		);
	}

	public function enable_dribbble_10_callback() {
		?> <fieldset><?php $checked = ( isset( $this->tend_tdsocialicons_class_options['enable_dribbble_10'] ) && $this->tend_tdsocialicons_class_options['enable_dribbble_10'] === 'block' ) ? 'checked' : '' ; ?>
		<label for="enable_dribbble_10-0"><input type="radio" name="tend_tdsocialicons_class_option_name[enable_dribbble_10]" id="enable_dribbble_10-0" value="block" <?php echo $checked; ?>> <?php _e('Enable','nuno-sarmento-socialicons'); ?></label><br>
		<?php $checked = ( isset( $this->tend_tdsocialicons_class_options['enable_dribbble_10'] ) && $this->tend_tdsocialicons_class_options['enable_dribbble_10'] === 'none' ) ? 'checked' : '' ; ?>
		<label for="enable_dribbble_10-1"><input type="radio" name="tend_tdsocialicons_class_option_name[enable_dribbble_10]" id="enable_dribbble_10-1" value="none" <?php echo $checked; ?>> <?php _e('Disable','nuno-sarmento-socialicons'); ?></label></fieldset> <?php
	}

	public function behance_11_callback() {
		printf(
			'<input class="regular-text" type="text" name="tend_tdsocialicons_class_option_name[behance_11]" id="behance_11" value="%s">',
			isset( $this->tend_tdsocialicons_class_options['behance_11'] ) ? esc_attr( $this->tend_tdsocialicons_class_options['behance_11']) : ''
		);
	}

	public function enable_behance_12_callback() {
		?> <fieldset><?php $checked = ( isset( $this->tend_tdsocialicons_class_options['enable_behance_12'] ) && $this->tend_tdsocialicons_class_options['enable_behance_12'] === 'block' ) ? 'checked' : '' ; ?>
		<label for="enable_behance_12-0"><input type="radio" name="tend_tdsocialicons_class_option_name[enable_behance_12]" id="enable_behance_12-0" value="block" <?php echo $checked; ?>> <?php _e('Enable','nuno-sarmento-socialicons'); ?></label><br>
		<?php $checked = ( isset( $this->tend_tdsocialicons_class_options['enable_behance_12'] ) && $this->tend_tdsocialicons_class_options['enable_behance_12'] === 'none' ) ? 'checked' : '' ; ?>
		<label for="enable_behance_12-1"><input type="radio" name="tend_tdsocialicons_class_option_name[enable_behance_12]" id="enable_behance_12-1" value="none" <?php echo $checked; ?>> <?php _e('Disable','nuno-sarmento-socialicons'); ?></label></fieldset> <?php
	}

	public function googleplus_13_callback() {
		printf(
			'<input class="regular-text" type="text" name="tend_tdsocialicons_class_option_name[googleplus_13]" id="googleplus_13" value="%s">',
			isset( $this->tend_tdsocialicons_class_options['googleplus_13'] ) ? esc_attr( $this->tend_tdsocialicons_class_options['googleplus_13']) : ''
		);
	}

	public function enable_googleplus_14_callback() {
		?> <fieldset><?php $checked = ( isset( $this->tend_tdsocialicons_class_options['enable_googleplus_14'] ) && $this->tend_tdsocialicons_class_options['enable_googleplus_14'] === 'block' ) ? 'checked' : '' ; ?>
		<label for="enable_googleplus_14-0"><input type="radio" name="tend_tdsocialicons_class_option_name[enable_googleplus_14]" id="enable_googleplus_14-0" value="block" <?php echo $checked; ?>> <?php _e('Enable','nuno-sarmento-socialicons'); ?></label><br>
		<?php $checked = ( isset( $this->tend_tdsocialicons_class_options['enable_googleplus_14'] ) && $this->tend_tdsocialicons_class_options['enable_googleplus_14'] === 'none' ) ? 'checked' : '' ; ?>
		<label for="enable_googleplus_14-1"><input type="radio" name="tend_tdsocialicons_class_option_name[enable_googleplus_14]" id="enable_googleplus_14-1" value="none" <?php echo $checked; ?>> <?php _e('Disable','nuno-sarmento-socialicons'); ?></label></fieldset> <?php
	}

	public function colorpicker_15_callback() {
    $val = ( isset( $this->tend_tdsocialicons_class_options['colorpicker_15'] ) ) ? $this->tend_tdsocialicons_class_options['colorpicker_15'] : '';
    echo '<input type="text" name="tend_tdsocialicons_class_option_name[colorpicker_15]" value="' . $val . '" class="tend-tdss-color-picker" >';
	}

	public function colorpicker_16_callback() {
    $val = ( isset( $this->tend_tdsocialicons_class_options['colorpicker_16'] ) ) ? $this->tend_tdsocialicons_class_options['colorpicker_16'] : '';
    echo '<input type="text" name="tend_tdsocialicons_class_option_name[colorpicker_16]" value="' . $val . '" class="tend-tdss-color-picker" >';
	}

	public function colorpicker_17_callback() {
    $val = ( isset( $this->tend_tdsocialicons_class_options['colorpicker_17'] ) ) ? $this->tend_tdsocialicons_class_options['colorpicker_17'] : '';
    echo '<input type="text" name="tend_tdsocialicons_class_option_name[colorpicker_17]" value="' . $val . '" class="tend-tdss-color-picker" >';
	}

	public function colorpicker_18_callback() {
    $val = ( isset( $this->tend_tdsocialicons_class_options['colorpicker_18'] ) ) ? $this->tend_tdsocialicons_class_options['colorpicker_18'] : '';
    echo '<input type="text" name="tend_tdsocialicons_class_option_name[colorpicker_18]" value="' . $val . '" class="tend-tdss-color-picker" >';
	}

	public function colorpicker_19_callback() {
		$val = ( isset( $this->tend_tdsocialicons_class_options['colorpicker_19'] ) ) ? $this->tend_tdsocialicons_class_options['colorpicker_19'] : '';
		echo '<input type="text" name="tend_tdsocialicons_class_option_name[colorpicker_19]" value="' . $val . '" class="tend-tdss-color-picker" >';
	}

	public function colorpicker_20_callback() {
		$val = ( isset( $this->tend_tdsocialicons_class_options['colorpicker_20'] ) ) ? $this->tend_tdsocialicons_class_options['colorpicker_20'] : '';
		echo '<input type="text" name="tend_tdsocialicons_class_option_name[colorpicker_20]" value="' . $val . '" class="tend-tdss-color-picker" >';
	}


	public function ns_socialicons_about_callback() {

				?>
		<h1>'Nuno Sarmento' Plugins Colection</h1>

			<div class="wrap">

					<p class="clear"></p>

							<div class="plugin-group">

								<div class="plugin-card">

									 <div class="plugin-card-top">

											 <a href="https://en-gb.wordpress.org/plugins/nuno-sarmento-slick-slider/" class="plugin-icon" target="_blank">
											 	 <style type="text/css">#plugin-icon-nuno-sarmento-slick-slider { width:128px; height:128px; background-image: url(//ps.w.org/nuno-sarmento-slick-slider/assets/icon-128x128.png?rev=1588561); background-size:128px 128px; }@media only screen and (-webkit-min-device-pixel-ratio: 1.5) { #plugin-icon-nuno-sarmento-slick-slider { background-image: url(//ps.w.org/nuno-sarmento-slick-slider/assets/icon-256x256.png?rev=1588561); } }</style>
												 <div class="plugin-icon" id="plugin-icon-nuno-sarmento-slick-slider" style="float:left; margin: 3px 6px 6px 0px;"></div>
											 </a>

											 <div class="name column-name" style="float: right;">
											    <h4><a href="https://en-gb.wordpress.org/plugins/nuno-sarmento-slick-slider/" target="_blank">Nuno Sarmento Slick Slider</a></h4>
										 	 </div>

									</div>

									<div class="plugin-card-bottom">
										<p class="authors"><cite>By: <a href="//profiles.wordpress.org/nunosarmento/" target="_blank">Nuno Morais Sarmento</a>.</cite></p>
									</div>

								</div>

								<div class="plugin-card">

									 <div class="plugin-card-top">

											 <a href="https://en-gb.wordpress.org/plugins/nuno-sarmento-custom-css-js/" class="plugin-icon" target="_blank">
											 	 <style type="text/css">#plugin-icon-nuno-sarmento-custom-css-js { width:128px; height:128px; background-image: url(//ps.w.org/nuno-sarmento-custom-css-js/assets/icon-128x128.png?rev=1588566); background-size:128px 128px; }@media only screen and (-webkit-min-device-pixel-ratio: 1.5) { #plugin-icon-nuno-sarmento-custom-css-js { background-image: url(//ps.w.org/nuno-sarmento-custom-css-js/assets/icon-256x256.png?rev=1588566); } }</style>
												 <div class="plugin-icon" id="plugin-icon-nuno-sarmento-custom-css-js" style="float:left; margin: 3px 6px 6px 0px;"></div>
											 </a>

											 <div class="name column-name" style="float: right;">
											 		<h4><a href="https://en-gb.wordpress.org/plugins/nuno-sarmento-custom-css-js/" target="_blank">Nuno Sarmento Custom CSS - JS</a></h4>
										 	 </div>

									</div>

									<div class="plugin-card-bottom">
										<p class="authors"><cite>By: <a href="//profiles.wordpress.org/nunosarmento/" target="_blank">Nuno Morais Sarmento</a>.</cite></p>
									</div>

								</div>

								<div class="plugin-card">

									 <div class="plugin-card-top">

											 <a href="https://en-gb.wordpress.org/plugins/nuno-sarmento-social-icons/" class="plugin-icon" target="_blank">
												 <style type="text/css">#plugin-icon-nuno-sarmento-social-icons { width:128px; height:128px; background-image: url(//ps.w.org/nuno-sarmento-social-icons/assets/icon-128x128.png?rev=1588574); background-size:128px 128px; }@media only screen and (-webkit-min-device-pixel-ratio: 1.5) { #plugin-icon-nuno-sarmento-social-icons { background-image: url(//ps.w.org/nuno-sarmento-social-icons/assets/icon-256x256.png?rev=1588574); } }</style>
												 <div class="plugin-icon" id="plugin-icon-nuno-sarmento-social-icons" style="float:left; margin: 3px 6px 6px 0px;"></div>
											 </a>

											 <div class="name column-name" style="float: right;">
											 		<h4><a href="https://en-gb.wordpress.org/plugins/nuno-sarmento-social-icons/" target="_blank">Nuno Sarmento Social Icons</a></h4>
										 	 </div>

									</div>

									<div class="plugin-card-bottom">
										<p class="authors"><cite>By: <a href="//profiles.wordpress.org/nunosarmento/" target="_blank">Nuno Morais Sarmento</a>.</cite></p>
									</div>

								</div>

								<div class="plugin-card">

									 <div class="plugin-card-top">

										 <a href="https://en-gb.wordpress.org/plugins/nuno-sarmento-page-builder/" class="plugin-icon" target="_blank">
										 	  <style type="text/css">#plugin-icon-nuno-sarmento-page-builder { width:128px; height:128px; background-image: url(//ps.w.org/nuno-sarmento-page-builder/assets/icon-128x128.png?rev=1588552); background-size:128px 128px; }@media only screen and (-webkit-min-device-pixel-ratio: 1.5) { #plugin-icon-nuno-sarmento-page-builder { background-image: url(//ps.w.org/nuno-sarmento-page-builder/assets/icon-256x256.png?rev=1588552); } }</style>
										 	  <div class="plugin-icon" id="plugin-icon-nuno-sarmento-page-builder" style="float:left; margin: 3px 6px 6px 0px;"></div>
									 	 </a>

										 <div class="name column-name" style="float: right;">
										 <h4><a href="https://en-gb.wordpress.org/plugins/nuno-sarmento-page-builder/" target="_blank">Nuno Sarmento Page Builder</a></h4>

									 </div>

									</div>

									<div class="plugin-card-bottom">
										<p class="authors"><cite>By: <a href="//profiles.wordpress.org/nunosarmento/" target="_blank">Nuno Morais Sarmento</a>.</cite></p>
									</div>

								</div>

								<div class="plugin-card">

									 <div class="plugin-card-top">

											 <a href="https://en-gb.wordpress.org/plugins/nuno-sarmento-popup/" class="plugin-icon" target="_blank">
												 <style type="text/css">#plugin-icon-nuno-sarmento-popup { width:128px; height:128px; background-image: url(//ps.w.org/nuno-sarmento-popup/assets/icon-128x128.png?rev=1593940); background-size:128px 128px; }@media only screen and (-webkit-min-device-pixel-ratio: 1.5) { #plugin-icon-nuno-sarmento-popup { background-image: url(//ps.w.org/nuno-sarmento-popup/assets/icon-256x256.png?rev=1593940); } }</style>
												 <div class="plugin-icon" id="plugin-icon-nuno-sarmento-popup" style="float:left; margin: 3px 6px 6px 0px;"></div>
											 </a>

											 <div class="name column-name" style="float: right;">
											    <h4><a href="https://en-gb.wordpress.org/plugins/nuno-sarmento-popup/" target="_blank" >Nuno Sarmento PopUp</a></h4>
										   </div>

									</div>

									<div class="plugin-card-bottom">
										<p class="authors"><cite>By: <a href="//profiles.wordpress.org/nunosarmento/" target="_blank">Nuno Morais Sarmento</a>.</cite></p>
									</div>

							 </div>


							 <div class="plugin-card">

							 	 <div class="plugin-card-top">

							 		 <a href="https://en-gb.wordpress.org/plugins/nuno-sarmento-api-to-post/" class="plugin-icon">
										 <style type="text/css">#plugin-icon-nuno-sarmento-api-to-post { width:128px; height:128px; background-image: url(//ps.w.org/nuno-sarmento-api-to-post/assets/icon-128x128.png?rev=1594469); background-size:128px 128px; }@media only screen and (-webkit-min-device-pixel-ratio: 1.5) { #plugin-icon-nuno-sarmento-api-to-post { background-image: url(//ps.w.org/nuno-sarmento-api-to-post/assets/icon-256x256.png?rev=1594469); } }</style>
										 <div class="plugin-icon" id="plugin-icon-nuno-sarmento-api-to-post" style="float:left; margin: 3px 6px 6px 0px;"></div>
								 	 </a>

							 		 <div class="name column-name">
							 			 <h4><a href="https://en-gb.wordpress.org/plugins/nuno-sarmento-api-to-post/">Nuno Sarmento API To Post</a></h4>
							 		 </div>

							 	</div>

								<div class="plugin-card-bottom">
									<p class="authors"><cite>By: <a href="//profiles.wordpress.org/nunosarmento/" target="_blank">Nuno Morais Sarmento</a>.</cite></p>
								</div>

							 </div>

						</div>

				  </div>

			<?php

		}

		public function ns_socialicons_snapshot_report() {

			?>
				<div class="wrap nuno-sarmento-system-wrap">
					<div class="icon32" id="icon-tools"><br></div>
					<h2><?php _e( 'System Report', 'nuno-sarmento-social-icons' ) ?></h2>
					<p><?php echo $this->ns_socialicons_snapshot_data(); ?></p>
				</div>
				<style media="screen">
					div.nuno-sarmento-system-wrap h2 {margin: 0 0 1em;}
					div.nuno-sarmento-system-wrap p {margin: 0 0 1em;}
					div.nuno-sarmento-system-wrap p input.snapshot-highlight {margin: 0 0 0 10px;}
					div.nuno-sarmento-system-wrap textarea#nuno-sarmento-system-textarea {
					background: #ebebeb;display: block;font-family: Menlo,Monaco,monospace;height: 600px;overflow: auto;white-space: pre;width: 1500px;max-width: 95%;color: #000;padding: 10px 0 10px 10px;}
				</style>
		 <?php

		}

		public function ns_socialicons_snapshot_data() {

			// call WP database
			global $wpdb;

			// check for browser class add on
			if ( ! class_exists( 'Browser' ) ) {
				require_once NUNO_SARMENTO_SOCIALICONS_PATH . 'includes/ns-socialicons-browser.php';
			}

			// do WP version check and get data accordingly
			$browser = new Browser();
			if ( get_bloginfo( 'version' ) < '3.4' ) :
				$theme_data = get_theme_data( get_stylesheet_directory() . '/style.css' );
				$theme      = $theme_data['Name'] . ' ' . $theme_data['Version'];
			else:
				$theme_data = wp_get_theme();
				$theme      = $theme_data->Name . ' ' . $theme_data->Version;
			endif;

			// data checks for later
			$frontpage	= get_option( 'page_on_front' );
			$frontpost	= get_option( 'page_for_posts' );
			$mu_plugins = get_mu_plugins();
			$plugins	= get_plugins();
			$active		= get_option( 'active_plugins', array() );

			// multisite details
			$nt_plugins	= is_multisite() ? wp_get_active_network_plugins() : array();
			$nt_active	= is_multisite() ? get_site_option( 'active_sitewide_plugins', array() ) : array();
			$ms_sites	= is_multisite() ? get_blog_list() : null;

			// yes / no specifics
			$ismulti	= is_multisite() ? __( 'Yes', 'nuno-sarmento-system-report' ) : __( 'No', 'nuno-sarmento-system-report' );
			$safemode	= ini_get( 'safe_mode' ) ? __( 'Yes', 'nuno-sarmento-system-report' ) : __( 'No', 'nuno-sarmento-system-report' );
			$wpdebug	= defined( 'WP_DEBUG' ) ? WP_DEBUG ? __( 'Enabled', 'nuno-sarmento-system-report' ) : __( 'Disabled', 'nuno-sarmento-system-report' ) : __( 'Not Set', 'nuno-sarmento-system-report' );
			$tbprefx	= strlen( $wpdb->prefix ) < 16 ? __( 'Acceptable', 'nuno-sarmento-system-report' ) : __( 'Too Long', 'nuno-sarmento-system-report' );
			$fr_page	= $frontpage ? get_the_title( $frontpage ).' (ID# '.$frontpage.')'.'' : __( 'n/a', 'nuno-sarmento-system-report' );
			$fr_post	= $frontpage ? get_the_title( $frontpost ).' (ID# '.$frontpost.')'.'' : __( 'n/a', 'nuno-sarmento-system-report' );
			$errdisp	= ini_get( 'display_errors' ) != false ? __( 'On', 'nuno-sarmento-system-report' ) : __( 'Off', 'nuno-sarmento-system-report' );

			$jquchk		= wp_script_is( 'jquery', 'registered' ) ? $GLOBALS['wp_scripts']->registered['jquery']->ver : __( 'n/a', 'nuno-sarmento-system-report' );

			$sessenb	= isset( $_SESSION ) ? __( 'Enabled', 'nuno-sarmento-system-report' ) : __( 'Disabled', 'nuno-sarmento-system-report' );
			$usecck		= ini_get( 'session.use_cookies' ) ? __( 'On', 'nuno-sarmento-system-report' ) : __( 'Off', 'nuno-sarmento-system-report' );
			$useocck	= ini_get( 'session.use_only_cookies' ) ? __( 'On', 'nuno-sarmento-system-report' ) : __( 'Off', 'nuno-sarmento-system-report' );
			$hasfsock	= function_exists( 'fsockopen' ) ? __( 'Supports fsockopen.', 'nuno-sarmento-system-report' ) : __( 'Not support fsockopen.', 'nuno-sarmento-system-report' );
			$hascurl	= function_exists( 'curl_init' ) ? __( 'Supports cURL.', 'nuno-sarmento-system-report' ) : __( 'Not support cURL.', 'nuno-sarmento-system-report' );
			$hassoap	= class_exists( 'SoapClient' ) ? __( 'SOAP Client enabled.', 'nuno-sarmento-system-report' ) : __( 'Does not have the SOAP Client enabled.', 'nuno-sarmento-system-report' );
			$hassuho	= extension_loaded( 'suhosin' ) ? __( 'Server has SUHOSIN installed.', 'nuno-sarmento-system-report' ) : __( 'Does not have SUHOSIN installed.', 'nuno-sarmento-system-report' );
			$openssl	= extension_loaded('openssl') ? __( 'OpenSSL installed.', 'nuno-sarmento-system-report' ) : __( 'Does not have OpenSSL installed.', 'nuno-sarmento-system-report' );

			// start generating report
			$report	= '';
			$report	.= '<textarea readonly="readonly" id="nuno-sarmento-system-textarea" name="nuno-sarmento-system-textarea">';
			$report	.= '--- Begin System Info ---'."\n";
			// add filter for adding to report opening
			$report	.= apply_filters( 'snapshot_report_before', '' );

			$report	.= "\n\t".'-- SERVER DATA --'."\n";
			$report	.= 'jQuery Version'."\t\t\t\t".$jquchk."\n";
			$report	.= 'PHP Version:'."\t\t\t\t".PHP_VERSION."\n";
			$report	.= 'MySQL Version:'."\t\t\t\t".$wpdb->db_version()."\n";
			$report	.= 'Server Software:'."\t\t\t".$_SERVER['SERVER_SOFTWARE']."\n";

			$report	.= "\n\t".'-- PHP CONFIGURATION --'."\n";
			$report	.= 'Safe Mode:'."\t\t\t\t".$safemode."\n";
			$report	.= 'Memory Limit:'."\t\t\t\t".ini_get( 'memory_limit' )."\n";
			$report	.= 'Upload Max:'."\t\t\t\t".ini_get( 'upload_max_filesize' )."\n";
			$report	.= 'Post Max:'."\t\t\t\t".ini_get( 'post_max_size' )."\n";
			$report	.= 'Time Limit:'."\t\t\t\t".ini_get( 'max_execution_time' )."\n";
			$report	.= 'Max Input Vars:'."\t\t\t\t".ini_get( 'max_input_vars' )."\n";
			$report	.= 'Display Errors:'."\t\t\t\t".$errdisp."\n";
			$report	.= 'Sessions:'."\t\t\t\t".$sessenb."\n";
			$report	.= 'Session Name:'."\t\t\t\t".esc_html( ini_get( 'session.name' ) )."\n";
			$report	.= 'Cookie Path:'."\t\t\t\t".esc_html( ini_get( 'session.cookie_path' ) )."\n";
			$report	.= 'Save Path:'."\t\t\t\t".esc_html( ini_get( 'session.save_path' ) )."\n";
			$report	.= 'Use Cookies:'."\t\t\t\t".$usecck."\n";
			$report	.= 'Use Only Cookies:'."\t\t\t".$useocck."\n";
			$report	.= 'FSOCKOPEN:'."\t\t\t\t".$hasfsock."\n";
			$report	.= 'cURL:'."\t\t\t\t\t".$hascurl."\n";
			$report	.= 'SOAP Client:'."\t\t\t\t".$hassoap."\n";
			$report	.= 'SUHOSIN:'."\t\t\t\t".$hassuho."\n";
			$report	.= 'OpenSSL:'."\t\t\t\t".$openssl."\n";

			$report	.= "\n\t".'-- WORDPRESS DATA --'."\n";
			$report	.= 'Multisite:'."\t\t\t\t".$ismulti."\n";
			$report	.= 'SITE_URL:'."\t\t\t\t".site_url()."\n";
			$report	.= 'HOME_URL:'."\t\t\t\t".home_url()."\n";
			$report	.= 'WP Version:'."\t\t\t\t".get_bloginfo( 'version' )."\n";
			$report	.= 'Permalink:'."\t\t\t\t".get_option( 'permalink_structure' )."\n";
			$report	.= 'Cur Theme:'."\t\t\t\t".$theme."\n";
			$report	.= 'Post Types:'."\t\t\t\t".implode( ', ', get_post_types( '', 'names' ) )."\n";
			$report	.= 'Post Stati:'."\t\t\t\t".implode( ', ', get_post_stati() )."\n";
			$report	.= 'User Count:'."\t\t\t\t".count( get_users() )."\n";

			$report	.= "\n\t".'-- WORDPRESS CONFIG --'."\n";
			$report	.= 'WP_DEBUG:'."\t\t\t\t".$wpdebug."\n";
			$report	.= 'WP Memory Limit:'."\t\t\t".$this->num_convt( WP_MEMORY_LIMIT )/( 1024 ).'MB'."\n";
			$report	.= 'Table Prefix:'."\t\t\t\t".$wpdb->base_prefix."\n";
			$report	.= 'Prefix Length:'."\t\t\t\t".$tbprefx.' ('.strlen( $wpdb->prefix ).' characters)'."\n";
			$report	.= 'Show On Front:'."\t\t\t\t".get_option( 'show_on_front' )."\n";
			$report	.= 'Page On Front:'."\t\t\t\t".$fr_page."\n";
			$report	.= 'Page For Posts:'."\t\t\t\t".$fr_post."\n";

			if ( is_multisite() ) :
				$report	.= "\n\t".'-- MULTISITE INFORMATION --'."\n";
				$report	.= 'Total Sites:'."\t\t\t\t".get_blog_count()."\n";
				$report	.= 'Base Site:'."\t\t\t\t".$ms_sites[0]['domain']."\n";
				$report	.= 'All Sites:'."\n";
				foreach ( $ms_sites as $site ) :
					if ( $site['path'] != '/' )
						$report	.= "\t\t".'- '. $site['domain'].$site['path']."\n";

				endforeach;
				$report	.= "\n";
			endif;

			$report	.= "\n\t".'-- BROWSER DATA --'."\n";
			$report	.= 'Platform:'."\t\t\t\t".$browser->getPlatform()."\n";
			$report	.= 'Browser Name'."\t\t\t\t". $browser->getBrowser() ."\n";
			$report	.= 'Browser Version:'."\t\t\t".$browser->getVersion()."\n";
			$report	.= 'Browser User Agent:'."\t\t\t".$browser->getUserAgent()."\n";

			$report	.= "\n\t".'-- PLUGIN INFORMATION --'."\n";
			if ( $plugins && $mu_plugins ) :
				$report	.= 'Total Plugins:'."\t\t\t\t".( count( $plugins ) + count( $mu_plugins ) + count( $nt_plugins ) )."\n";
			endif;

			// output must-use plugins
			if ( $mu_plugins ) :
				$report	.= 'Must-Use Plugins: ('.count( $mu_plugins ).')'. "\n";
				foreach ( $mu_plugins as $mu_path => $mu_plugin ) :
					$report	.= "\t".'- '.$mu_plugin['Name'] . ' ' . $mu_plugin['Version'] ."\n";
				endforeach;
				$report	.= "\n";
			endif;

			// if multisite, grab active network as well
			if ( is_multisite() ) :
				// active network
				$report	.= 'Network Active Plugins: ('.count( $nt_plugins ).')'. "\n";

				foreach ( $nt_plugins as $plugin_path ) :
					if ( array_key_exists( $plugin_base, $nt_plugins ) )
						continue;

					$plugin = get_plugin_data( $plugin_path );

					$report	.= "\t".'- '.$plugin['Name'] . ' ' . $plugin['Version'] ."\n";
				endforeach;
				$report	.= "\n";

			endif;

			// output active plugins
			if ( $plugins ) :
				$report	.= 'Active Plugins: ('.count( $active ).')'. "\n";
				foreach ( $plugins as $plugin_path => $plugin ) :
					if ( ! in_array( $plugin_path, $active ) )
						continue;
					$report	.= "\t".'- '.$plugin['Name'] . ' ' . $plugin['Version'] ."\n";
				endforeach;
				$report	.= "\n";
			endif;

			// output inactive plugins
			if ( $plugins ) :
				$report	.= 'Inactive Plugins: ('.( count( $plugins ) - count( $active ) ).')'. "\n";
				foreach ( $plugins as $plugin_path => $plugin ) :
					if ( in_array( $plugin_path, $active ) )
						continue;
					$report	.= "\t".'- '.$plugin['Name'] . ' ' . $plugin['Version'] ."\n";
				endforeach;
				$report	.= "\n";
			endif;

			// add filter for end of report
			$report	.= apply_filters( 'snapshot_report_after', '' );

			// end it all
			$report	.= "\n".'--- End System Info ---';
			$report	.= '</textarea>';

			return $report;
		}


}

if ( is_admin() )
$tend_tdsocialicons_class = new NUNO_SARMENTO_SOCIAL_ICONS_Class();

 /* ------------------------------------------
 // Social Bar Output ----------------------------
 --------------------------------------------- */

 function ns_social_icons_get_social_bar($link = null, $title = null,  $imageurl = null) {

  $tend_tdsocialicons_class_options = get_option( 'tend_tdsocialicons_class_option_name' ); // Array of All Options
  $social_bar_disable_0 = $tend_tdsocialicons_class_options['social_bar_disable_0']; // Social bar (disable)
  $facebook_url_1 = $tend_tdsocialicons_class_options['facebook_url_1']; // Facebook url
  $enable_facebook_2 = $tend_tdsocialicons_class_options['enable_facebook_2']; // Enable Facebook
  $linkedin_3 = $tend_tdsocialicons_class_options['linkedin_3']; // Linkedin
  $enable_linkedin_4 = $tend_tdsocialicons_class_options['enable_linkedin_4']; // Enable Linkedin
  $twitter_5 = $tend_tdsocialicons_class_options['twitter_5']; // Twitter
  $enable_twitter_6 = $tend_tdsocialicons_class_options['enable_twitter_6']; // Enable Twitter
  $instagram_7 = $tend_tdsocialicons_class_options['instagram_7']; // Instagram
  $enable_instagram_8 = $tend_tdsocialicons_class_options['enable_instagram_8']; // Enable Instagram
  $dribbble_9 = $tend_tdsocialicons_class_options['dribbble_9']; // Dribbble
  $enable_dribbble_10 = $tend_tdsocialicons_class_options['enable_dribbble_10']; // Enable Dribbble
  $behance_11 = $tend_tdsocialicons_class_options['behance_11']; // Behance
  $enable_behance_12 = $tend_tdsocialicons_class_options['enable_behance_12']; // Enable Behance
	$googleplus_13 = $tend_tdsocialicons_class_options['googleplus_13']; // googleplus
	//$enable_googleplus_14 = $tend_tdsocialicons_class_options['enable_googleplus_14']; // Enable googleplus
	$enable_googleplus_14  = (isset($_GET['enable_googleplus_14'])) ? $_GET['enable_googleplus_14'] : 0; // Enable googleplus

	$link =  get_permalink();  // Get link
	$title =  get_the_title();  // Get title
	$thumb_id = get_post_thumbnail_id(); // Get thumbnail
	$thumb_url = wp_get_attachment_image_src($thumb_id, true);
	$imageurl = $imageurl ?: $thumb_url[0];
	$fb_sharer_url = "http://www.facebook.com/sharer/sharer.php?s=100&amp;p[url]={$link}&amp;p[images][0]={$imageurl}&amp;p[title]={$title}";
	$tweet = get_the_title();
	$twitter_url = "http://twitter.com/share?url={$link}&text={$tweet}";
	$plusone_url = "https://plus.google.com/share?url={$link}";

  $output_socialbar =  '
		<div class="nuno-sarmento-socialicons-nav__bar">
		   <nav style="display:'.$social_bar_disable_0.'; "  class="tend_tdsocialicons_social">
		  		 <ul class="ns__social_list">
		  				 <li style="display:'.$enable_facebook_2.'"><a href="'.$facebook_url_1.'/sharer.php?u=' . esc_url( get_permalink() ) . '&amp;t=' . $title . '" title="Share on Facebook." onclick="PopupCenter(\''. $fb_sharer_url .'\', \'600\', \'345\') ;return false;">' . esc_html__( 'Facebook', 'nuno-sarmento-socialicons' ) . '<i class="fa fa-facebook"></i></a></li>
		  				 <li style="display:'.$enable_twitter_6.'"><a href="'.$twitter_5.'/home/?status='. $tweet .'-' . esc_url( get_permalink() ) . '" title="Tweet this!" onclick="PopupCenter(\''. $twitter_url .'\', \'500\', \'250\') ;return false; ">' . esc_html__( 'Twitter', 'nuno-sarmento-socialicons' ) . '<i class="fa fa-twitter"></i></a></li>
							 <li style="display:'.$enable_googleplus_14.'"><a href="'.$googleplus_13.'/share?url=' . esc_url( get_permalink() ) . '"  onclick="PopupCenter(\''.$plusone_url.'\', \'500\', \'450\' , \'menubar=no\' , \'toolbar=no\', \'resizable=yes\' , \'scrollbars=yes\') ;return false;"> ' . esc_html__( 'Google+', 'nuno-sarmento-socialicons' ) . '<i class="fa fa-google-plus"></i></a></li>
							 <li style="display:'.$enable_instagram_8.'"><a href="'.$instagram_7.'">' . esc_html__( 'Instagram', 'nuno-sarmento-socialicons' ) . '<i class="fa fa-instagram"></i></a></li>
							 <li style="display:'.$enable_linkedin_4.'"><a href="'.$linkedin_3.'/shareArticle?mini=true&amp;title='. $title .'&amp;url=' . esc_url( get_permalink() ) . '" title="Share on LinkedIn">' . esc_html__( 'Linkedin', 'nuno-sarmento-socialicons' ) . '<i class="fa fa-linkedin"></i></a></li>
		  				 <li style="display:'.$enable_dribbble_10.'"><a href="'.$dribbble_9.'">' . esc_html__( 'Dribbble', 'nuno-sarmento-socialicons' ) . '<i class="fa fa-dribbble"></i></a></li>
		  				 <li style="display:'.$enable_behance_12.'"><a href="'.$behance_11.'">' . esc_html__( 'Behance', 'nuno-sarmento-socialicons' ) . '<i class="fa fa-behance"></i></a></li>
		  		 </ul>
		   </nav>
	  </div>
	 ';

  echo $output_socialbar ;

 }
 add_action('wp_footer', 'ns_social_icons_get_social_bar', 100);
